name: 'planemo discover'
description: 'Installs planemo and discovers changed repositories of tools or workflows'
author: 'iuc@galaxyproject.org'
inputs:
  create-cache: 
    description: 'Set false if creating a cache is not needed'
    default: false
  planemo-version:
    description: 'Set a specific planemo version or url. If not specified installs latest planemo release from PyPI'
    default: 'planemo'
  galaxy-branch:
    description: 'Galaxy branch to use'
    default: 'master'
  galaxy-source:
    description: 'Galaxy repository to use'
    default: 'https://github.com/galaxyproject/galaxy'
  changed-repositories:
    description: 'List of changed repositories. Only needed if running parallel jobs.'
    default: ''
  lint-tools:
    descriptions: 'Lint planemo tools?'
    default: false
  test-tools:
    description: 'Run planemo tests?'
    default: false
  test-workflows:
    description: 'Run workflow tests?'
    default: false
  shed-update:
    description: 'Upload tools to toolshed (after successfull test)?'
    default: false
  workflow-upload:
    description: 'Upload workflow to github organization'
    default: false
  workflow-namespace:
    description: 'Github namespace under which to create workfow repositories'
    default: 'iwc-workflows'
  github-token:
    description: '(Secret!) Github PAT token. Needed for creating workflow repositories with workflow-upload'
    default: ''
  chunk-count:
    description: 'Number of tests to run in parallel'
    default: 1
  database_connection:
    description: 'Database connection to use for tests'
    default: 'postgresql://postgres:postgres@localhost:5432/galaxy'
  chunk:
    description: 'Current test chunk'
    default: 0
  combine-outputs:
    descripttion: 'Combine multiple test reports into a single output'
    default: false
  html-report:
    description: 'Create HTML report?'
    default: false
  markdown-report:
    description: 'Create markdown report?'
    default: false
  shed-target:
    description: 'Which toolshed to target?'
    default: 'toolshed'
  shed-key:
    description: '(Secret!) tool shed api key'
    default: ''

outputs:
  changed-repositories:
    description: 'List of changed repositories'
    value: ${{ steps.changed-repositories.outputs.changed-repositories }}
runs:
  using: 'composite'
  steps:
    - run: pip install wheel ${{ inputs.planemo-version }}
      shell: bash
    - name: run planemo actions
      run: ${{ github.action_path }}/planemo_ci_actions.sh
      shell: bash
      env:
        EVENT_BEFORE: ${{ github.event.before }}
        CREATE_CACHE: ${{ inputs.create-cache }}
        GALAXY_BRANCH: ${{ inputs.galaxy-branch }}
        GALAXY_SOURCE: ${{ inputs.galaxy-source }}
        CHANGED_REPOSITORIES: ${{ inputs.changed-repositories}}
        CHUNK: ${{ inputs.chunk }}
        CHUNK_COUNT: ${{ inputs.chunk-count}}
        DATABASE_CONNECTION: ${{ inputs.database-connection }}
        PLANEMO_LINT_TOOLS: ${{ inputs.lint-tools }}
        PLANEMO_TEST_TOOLS: ${{ inputs.test-tools }}
        PLANEMO_TEST_WORKFLOWS: ${{ inputs.test-workflows }}
        PLANEMO_SHED_UPDATE: ${{ inputs.shed-update }}
        PLANEMO_WORKFLOW_UPLOAD: ${{ inputs.workflow-upload }}
        PLANEMO_WORKFLOW_NAMESPACE: ${{ inputs.workflow-namespace }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PLANEMO_COMBINE_OUTPUTS: ${{ inputs.combine-outputs }}
        PLANEMO_HTML_REPORT: ${{ inputs.html-report }}
        PLANEMO_MD_REPORT: ${{ inputs.markdown-report }}
        SHED_TARGET: ${{ inputs.shed-target }}
        SHED_KEY: ${{ inputs.shed-key }}
    - run: echo "::set-output name=changed-repositories::$(cat changed_repositories.list)"
      id: changed-repositories
      shell: bash
      
