name: 'planemo discover'
description: 'Installs planemo and discovers changed repositories of tools or workflows'
author: 'iuc@galaxyproject.org'
inputs:
  create-cache: 
    description: 'Set false if creating a cache is not needed'
    default: false
  planemo-version:
    description: 'Set a specific planemo version or url. If not specified installs latest planemo release from PyPI'
    default: 'planemo'
  galaxy-branch:
    description: 'Galaxy branch to use'
    default: 'master'
  galaxy-source:
    description: 'Galaxy repository to use'
    default: 'https://github.com/galaxyproject/galaxy'
  python-version:
    description: 'Python version to use'
    default: '3.7'
  repositories:
    description: 'List of repositories.'
    default: ''
  lint-tools:
    descriptions: 'Lint planemo tools?'
    default: false
  test-tools:
    description: 'Run planemo tests?'
    default: false
  deploy-tools:
    description: 'Upload tools to toolshed (after successfull test)?'
    default: false
  chunk-count:
    description: 'Number of tests to run in parallel'
    default: 20
  database_connection:
    description: 'Database connection to use for tests'
    default: 'postgresql://postgres:postgres@localhost:5432/galaxy'
  chunk:
    description: 'Current test chunk'
    default: 0
  combine-outputs:
    descripttion: 'Combine multiple test reports into a single output'
    default: false
  html-report:
    description: 'Create HTML report?'
    default: false
  markdown-report:
    description: 'Create markdown report?'
    default: false
  shed-target:
    description: 'Which toolshed to target?'
    default: 'toolshed'
  shed-key:
    description: '(Secret!) tool shed api key'
    default: 'toolshed'

outputs:
  repositories:
    description: 'List of changed repositories'
    value: ${{ steps.repositories.outputs.repositories }}
  commit-range:
    description: 'Commit range'
    value: ${{ steps.commit_range.outputs.commit_range }}
runs:
  using: 'composite'
  steps:
    - run: pip install wheel ${{ inputs.planemo-version }}
      shell: bash
    - name: run planemo actions
      run: ${{ github.action_path }}/planemo_ci_actions.sh
      shell: bash
      env:
        EVENT_BEFORE: ${{ github.event.before }}
        CREATE_CACHE: ${{ inputs.create-cache }}
        GALAXY_BRANCH: ${{ inputs.galaxy-branch }}
        GALAXY_SOURCE: ${{ inputs.galaxy-source }}
        PYTHON_VERSION: ${{ inputs.python-version }}
        REPOSITORIES: ${{ inputs.repositories}}
        CHUNK: ${{ inputs.chunk }}
        CHUNK_COUNT: ${{ inputs.chunk-count}}
        DATABASE_CONNECTION: ${{ inputs.database-connection }}
        PLANEMO_LINT_TOOLS: ${{ inputs.lint-tools }}
        PLANEMO_TEST_TOOLS: ${{ inputs.test-tools }}
        PLANEMO_DEPLOY_TOOLS: ${{ inputs.deploy-tools }}
        PLANEMO_COMBINE_OUTPUTS: ${{ inputs.combine-outputs }}
        PLANEMO_HTML_REPORT: ${{ inputs.html-report }}
        PLANEMO_MD_REPORT: ${{ inputs.markdown-report }}
        SHED_TARGET: ${{ inputs.shed-target }}
        SHED_KEY: ${{ inputs.shed-key }}
    - run: echo "::set-output name=repositories::$(cat repository_list.txt)"
      id: repositories
      shell: bash
    - run: echo "::set-output name=commit_range::$(cat commit_range.txt)"
      id: commit_range
      shell: bash
