name: 'planemo discover'
description: 'Installs planemo and discovers changed repositories of tools or workflows'
author: 'iuc@galaxyproject.org'
inputs:
  create-cache: 
    description: 'Set false if creating a cache is not needed'
    default: false
  planemo-version:
    description: 'Set a specific planemo version or url. If not specified installs latest planemo release from PyPI'
    default: 'planemo'
  galaxy-branch:
    description: 'Galaxy branch to use'
    default: 'master'
  galaxy-source:
    description: 'Galaxy repository to use'
    default: 'https://github.com/galaxyproject/galaxy'
  changed-repositories:
    description: 'List of changed repositories. Only needed if running parallel jobs.'
    default: ''
  lint-tools:
    descriptions: 'Lint planemo tools?'
    default: false
  test-tools:
    description: 'Run planemo tests?'
    default: false
  deploy-tools:
    description: 'Upload tools to toolshed (after successfull test)?'
    default: false
  chunk-count:
    description: 'Number of tests to run in parallel'
    default: 20
  database_connection:
    description: 'Database connection to use for tests'
    default: 'postgresql://postgres:postgres@localhost:5432/galaxy'
  chunk:
    description: 'Current test chunk'
    default: 0
  html-report:
    description: 'Create HTML report?'
    default: false
  markdown-report:
    description: 'Create markdown report?'
    default: false
  shed-target:
    description: 'Which toolshed to target?'
    default: 'toolshed'
  shed-key:
    description: '(Secret!) tool shed api key'
    default: 'toolshed'

outputs:
  changed-repositories:
    description: 'List of changed repositories'
    value: ${{ steps.changed-repositories.outputs.changed-repositories }}
runs:
  using: 'composite'
  steps:
    - run: pip install wheel ${{ inputs.planemo-version }}
      shell: bash
    - name: run planemo actions
      run: ${{ github.action_path }}/planemo_ci_actions.sh
      shell: bash
      env:
        EVENT_BEFORE: ${{ github.event.before }}
        CREATE_CACHE: ${{ inputs.create-cache }}
        GALAXY_BRANCH: ${{ inputs.galaxy-branch || env.GALAXY_BRANCH }}
        GALAXY_SOURCE: ${{ inputs.galaxy-source || env.GALAXY_SOURCE }}
        CHANGED_REPOSITORIES: ${{ inputs.changed-repositories}}
        CHUNK: ${{ inputs.chunk }}
        CHUNK_COUNT: ${{ inputs.chunk-count}}
        DATABASE_CONNECTION: ${{ inputs.database-connection }}
        PLANEMO_LINT_TOOLS: ${{ inputs.lint-tools }}
        PLANEMO_TEST_TOOLS: ${{ inputs.test-tools }}
        PLANEMO_DEPLOY_TOOLS: ${{ inputs.deploy-tools }}
        PLANEMO_COMBINE_OUTPUTS: ${{ inputs.test-tools }}
        PLANEMO_HTML_REPORT: ${{ inputs.html-report }}
        PLANEMO_MD_REPORT: ${{ inputs.markdown-report }}
        SHED_TARGET: ${{ inputs.shed-target }}
        SHED_KEY: ${{ inputs.shed-key }}
    - name: Find commit range to test
      run: ${{ github.action_path }}/commit_range.sh
      env:
        EVENT_BEFORE: ${{ github.event.before }}
      shell: bash
    - name: Find changed repositories
      run: planemo ci_find_repos --changed_in_commit_range $COMMIT_RANGE --exclude packages --exclude deprecated --exclude_from .tt_skip --output changed_repositories.list
      shell: bash
    - run: echo "::set-output name=changed-repositories::$(cat changed_repositories.list)"
      id: changed-repositories
      shell: bash
      
