on: [push, pull_request]

name: 'Trigger: Push action'

env:
  GALAXY_FORK: galaxyproject
  GALAXY_BRANCH: master
  MAX_CHUNKS: 4

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  
  lint:
    name: Test linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache .cache/pip
      uses: actions/cache@v2
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy-head-sha }}

    - name: Install wheel
      run: pip install wheel
    - name: Install Planemo and flake8
      run: pip install planemo flake8 flake8-import-order
    - name: Planemo lint tools
      # TODO uses: ./
      uses: bernt-matthias/planemo-ci-action@topic/ci-for-wf
      with:
        lint-mode: true
        repository-list: "test/tools/tool1%0D%0Atest/tools/tool2"
        tool-list: "test/tools/tool1/tool1.xml%0D%0Atest/tools/tool2/tool2.xml" 

    - name: Planemo lint workflows
      # TODO uses: ./
      uses: bernt-matthias/planemo-ci-action@topic/ci-for-wf
      with:
        lint-mode: true
        workflows: true
        repository-list: "test/tools/example3/"
        tool-list: "IGNORED AT THE MOMENT"